# Generated by Django 5.1.3 on 2024-11-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desceription',
            new_name='description',
        ),
    ]
